### ISSUE TITLE
java.lang.NullPointerException when invoking "com.javacodegeeks.concurrent.ConcurrentLinkedHashMap.clear()"

### ISSUE THREAD

**Issue by th0rb3n** [ggrandes-clones/ConcurrentLinkedHashMap-JavaCodeGeeks#1]
java.lang.NullPointerException
        at com.javacodegeeks.concurrent.ConcurrentLinkedHashMap$Segment.clear(ConcurrentLinkedHashMap.java:771)
        at com.javacodegeeks.concurrent.ConcurrentLinkedHashMap.clear(ConcurrentLinkedHashMap.java:1206)
        at com.openexchange.tools.oxfolder.memory.ConditionTreeMapManagement.stop(ConditionTreeMapManagement.java:159)
...

**Comment by th0rb3n** [comment]
Please pull that simple solution:

```
                    HashEntry<K, V> hashEntry = tab[i];
                    if (null != hashEntry) {
                        hashEntry.recordRemoval(header);
                        tab[i] = null;
                    }
```

Thx...
